# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Vision' do
pod 'SDWebImage', '~> 3.7.5’
pod 'AFNetworking', '~> 3.0.4'
pod 'MJRefresh', '~> 3.1.0'
pod 'FMDB', '~> 2.6'
end

target 'VisionTests' do

end

target 'VisionUITests' do

end

